package com.example.islamiclovers;

import androidx.appcompat.app.AppCompatActivity;

import android.graphics.Color;
import android.os.Bundle;
import android.text.SpannableString;
import android.text.style.ForegroundColorSpan;
import android.widget.Button;

public class harkaattanveen extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_harkaattanveen);
        Button b1=(Button)findViewById(R.id.button1);
        Button b2=(Button)findViewById(R.id.button2);
        Button b3=(Button)findViewById(R.id.button3);
        Button b4=(Button)findViewById(R.id.button4);
        Button b5=(Button)findViewById(R.id.button5);
        Button b6=(Button)findViewById(R.id.button6);
        Button b7=(Button)findViewById(R.id.button7);
        Button b8=(Button)findViewById(R.id.button8);
        Button b9=(Button)findViewById(R.id.button9);
        Button b10=(Button)findViewById(R.id.button10);
        Button b11=(Button)findViewById(R.id.button11);
        Button b12=(Button)findViewById(R.id.button12);
        Button b13=(Button)findViewById(R.id.button13);
        Button b14=(Button)findViewById(R.id.button14);
        Button b15=(Button)findViewById(R.id.button15);
        Button b16=(Button)findViewById(R.id.button16);
        Button b17=(Button)findViewById(R.id.button17);
        Button b18=(Button)findViewById(R.id.button18);
        Button b19=(Button)findViewById(R.id.button19);
        Button b20=(Button)findViewById(R.id.button20);
        Button b21=(Button)findViewById(R.id.button21);
        Button b22=(Button)findViewById(R.id.button22);
        Button b23=(Button)findViewById(R.id.button23);
        Button b24=(Button)findViewById(R.id.button24);
        Button b25=(Button)findViewById(R.id.button25);
        Button b26=(Button)findViewById(R.id.button26);
        Button b27=(Button)findViewById(R.id.button27);
        Button b28=(Button)findViewById(R.id.button28);
        Button b29=(Button)findViewById(R.id.button29);
        Button b30=(Button)findViewById(R.id.button30);
        b1.setText("");
        String s1="اَبَدًا";
        SpannableString ss1=  new SpannableString(s1);
        ss1.setSpan(new ForegroundColorSpan(Color.MAGENTA), 0, 1, 0);
        ss1.setSpan(new ForegroundColorSpan(Color.MAGENTA), 1, 2, 0);
        ss1.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        ss1.setSpan(new ForegroundColorSpan(Color.BLACK), 3, 4, 0);
        ss1.setSpan(new ForegroundColorSpan(Color.BLUE), 4, 5, 0);
        ss1.setSpan(new ForegroundColorSpan(Color.BLUE), 5, 6, 0);
        ss1.setSpan(new ForegroundColorSpan(Color.MAGENTA), 6, 7, 0);
        b3.setText(ss1);
        b2.setText("");
        String s2="اَحَدٌ";
        SpannableString ss2=  new SpannableString(s2);
        ss2.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        ss2.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        ss2.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        ss2.setSpan(new ForegroundColorSpan(Color.BLACK), 3, 4, 0);
        ss2.setSpan(new ForegroundColorSpan(Color.RED), 4, 5, 0);
        ss2.setSpan(new ForegroundColorSpan(Color.RED), 5, 6, 0);
        b2.setText(ss2);
        b1.setText("");
        String s3="اَخَذَ";
        SpannableString ss3=  new SpannableString(s3);
        ss3.setSpan(new ForegroundColorSpan(Color.RED), 0, 1, 0);
        ss3.setSpan(new ForegroundColorSpan(Color.RED), 1, 2, 0);
        ss3.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        ss3.setSpan(new ForegroundColorSpan(Color.BLACK), 3, 4, 0);
        ss3.setSpan(new ForegroundColorSpan(Color.BLUE), 4, 5, 0);
        ss3.setSpan(new ForegroundColorSpan(Color.BLUE), 5, 6, 0);
        b1.setText(ss3);
        b6.setText("");
        String s4="اَذِنَ";
        SpannableString ss4=  new SpannableString(s4);
        ss4.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss4.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        ss4.setSpan(new ForegroundColorSpan(Color.RED), 2, 3, 0);
        ss4.setSpan(new ForegroundColorSpan(Color.RED), 3, 4, 0);
        ss4.setSpan(new ForegroundColorSpan(Color.BLUE), 4, 5, 0);
        ss4.setSpan(new ForegroundColorSpan(Color.BLUE), 5, 6, 0);
        b6.setText(ss4);
        b5.setText("");
        String s5="اَمَرَ";
        SpannableString ss5=  new SpannableString(s5);
        ss5.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss5.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        ss5.setSpan(new ForegroundColorSpan(Color.BLUE), 2, 3, 0);
        ss5.setSpan(new ForegroundColorSpan(Color.BLUE), 3, 4, 0);
        ss5.setSpan(new ForegroundColorSpan(Color.MAGENTA), 4, 5, 0);
        ss5.setSpan(new ForegroundColorSpan(Color.MAGENTA), 5, 6, 0);
        b5.setText(ss5);
        b4.setText("");
        String s6="اَنَا";
        SpannableString ss6=  new SpannableString(s6);
        ss6.setSpan(new ForegroundColorSpan(Color.MAGENTA), 0, 1, 0);
        ss6.setSpan(new ForegroundColorSpan(Color.MAGENTA), 1, 2, 0);
        ss6.setSpan(new ForegroundColorSpan(Color.RED), 2, 3, 0);
        ss6.setSpan(new ForegroundColorSpan(Color.RED), 3, 4, 0);
        ss6.setSpan(new ForegroundColorSpan(Color.BLACK), 4, 5, 0);
        b4.setText(ss6);
        b9.setText("");
        String s7="بَخِلَ";
        SpannableString ss7=  new SpannableString(s7);
        ss7.setSpan(new ForegroundColorSpan(Color.MAGENTA), 0, 1, 0);
        ss7.setSpan(new ForegroundColorSpan(Color.MAGENTA), 1, 2, 0);
        ss7.setSpan(new ForegroundColorSpan(Color.BLUE), 2, 3, 0);
        ss7.setSpan(new ForegroundColorSpan(Color.BLUE), 3, 4, 0);
        ss7.setSpan(new ForegroundColorSpan(Color.BLACK), 4, 5, 0);
        ss7.setSpan(new ForegroundColorSpan(Color.BLACK), 5, 6, 0);
        b9.setText(ss7);
        b8.setText("");
        String s8="بَرَرَۃٍ";
        SpannableString ss8=  new SpannableString(s8);
        ss8.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        ss8.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        ss8.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        ss8.setSpan(new ForegroundColorSpan(Color.BLACK), 3, 4, 0);
        ss8.setSpan(new ForegroundColorSpan(Color.BLUE), 4, 5, 0);
        ss8.setSpan(new ForegroundColorSpan(Color.BLUE), 5, 6, 0);
        ss8.setSpan(new ForegroundColorSpan(Color.RED), 6, 7, 0);
        ss8.setSpan(new ForegroundColorSpan(Color.RED), 7, 8, 0);
        b8.setText(ss8);
        b7.setText("");
        String s9="جَعَلَ";
        SpannableString ss9=  new SpannableString(s9);
        ss9.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss9.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        ss9.setSpan(new ForegroundColorSpan(Color.BLUE), 2, 3, 0);
        ss9.setSpan(new ForegroundColorSpan(Color.BLUE), 3, 4, 0);
        ss9.setSpan(new ForegroundColorSpan(Color.BLACK), 4, 5, 0);
        ss9.setSpan(new ForegroundColorSpan(Color.BLACK), 5, 6, 0);
        b7.setText(ss9);
        b12.setText("");
        String s10="جَمَعَ";
        SpannableString ss10=  new SpannableString(s10);
        ss10.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss10.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        ss10.setSpan(new ForegroundColorSpan(Color.BLUE), 2, 3, 0);
        ss10.setSpan(new ForegroundColorSpan(Color.BLUE), 3, 4, 0);
        ss10.setSpan(new ForegroundColorSpan(Color.BLACK), 4, 5, 0);
        ss10.setSpan(new ForegroundColorSpan(Color.BLACK), 5, 6, 0);
        b12.setText(ss10);
        b11.setText("");
        String s11="حَسَدَ";
        SpannableString ss11=  new SpannableString(s11);
        ss11.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        ss11.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        ss11.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        ss11.setSpan(new ForegroundColorSpan(Color.BLACK), 3, 4, 0);
        ss11.setSpan(new ForegroundColorSpan(Color.RED), 4, 5, 0);
        ss11.setSpan(new ForegroundColorSpan(Color.RED), 5, 6, 0);
        b11.setText(ss11);
        b10.setText("");
        String s12="حَشَرَ";
        SpannableString ss12=  new SpannableString(s12);
        ss12.setSpan(new ForegroundColorSpan(Color.MAGENTA), 0, 1, 0);
        ss12.setSpan(new ForegroundColorSpan(Color.MAGENTA), 1, 2, 0);
        ss12.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        ss12.setSpan(new ForegroundColorSpan(Color.BLACK), 3, 4, 0);
        ss12.setSpan(new ForegroundColorSpan(Color.BLUE), 4, 5, 0);
        ss12.setSpan(new ForegroundColorSpan(Color.BLUE), 5, 6, 0);
        b10.setText(ss12);
        b15.setText("");
        String s13="حَشِیَ";
        SpannableString ss13=  new SpannableString(s13);
        ss13.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        ss13.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        ss13.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        ss13.setSpan(new ForegroundColorSpan(Color.BLACK), 3, 4, 0);
        ss13.setSpan(new ForegroundColorSpan(Color.BLUE), 4, 5, 0);
        ss13.setSpan(new ForegroundColorSpan(Color.BLUE), 5, 6, 0);
        b15.setText(ss13);
        b14.setText("");
        String s14="خَلَقَ";
        SpannableString ss14=  new SpannableString(s14);
        ss14.setSpan(new ForegroundColorSpan(Color.MAGENTA), 0, 1, 0);
        ss14.setSpan(new ForegroundColorSpan(Color.MAGENTA), 1, 2, 0);
        ss14.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        ss14.setSpan(new ForegroundColorSpan(Color.BLACK), 3, 4, 0);
        ss14.setSpan(new ForegroundColorSpan(Color.BLUE), 4, 5, 0);
        ss14.setSpan(new ForegroundColorSpan(Color.BLUE), 5, 6, 0);
        b14.setText(ss14);
        b13.setText("");
        String s15="خُلَقَ";
        SpannableString ss15=  new SpannableString(s15);
        ss15.setSpan(new ForegroundColorSpan(Color.RED), 0, 1, 0);
        ss15.setSpan(new ForegroundColorSpan(Color.RED), 1, 2, 0);
        ss15.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        ss15.setSpan(new ForegroundColorSpan(Color.BLACK), 3, 4, 0);
        ss15.setSpan(new ForegroundColorSpan(Color.BLUE), 4, 5, 0);
        ss15.setSpan(new ForegroundColorSpan(Color.BLUE), 5, 6, 0);
        b13.setText(ss15);
        b18.setText("");
        String s16="ذَکَرَ";
        SpannableString ss16=  new SpannableString(s16);
        ss16.setSpan(new ForegroundColorSpan(Color.RED), 0, 1, 0);
        ss16.setSpan(new ForegroundColorSpan(Color.RED), 1, 2, 0);
        ss16.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        ss16.setSpan(new ForegroundColorSpan(Color.BLACK), 3, 4, 0);
        ss16.setSpan(new ForegroundColorSpan(Color.BLUE), 4, 5, 0);
        ss16.setSpan(new ForegroundColorSpan(Color.BLUE), 5, 6, 0);
        b18.setText(ss16);
        b17.setText("");
        String s17="رَفَعَ";
        SpannableString ss17=  new SpannableString(s17);
        ss17.setSpan(new ForegroundColorSpan(Color.MAGENTA), 0, 1, 0);
        ss17.setSpan(new ForegroundColorSpan(Color.MAGENTA), 1, 2, 0);
        ss17.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        ss17.setSpan(new ForegroundColorSpan(Color.BLACK), 3, 4, 0);
        ss17.setSpan(new ForegroundColorSpan(Color.RED), 4, 5, 0);
        ss17.setSpan(new ForegroundColorSpan(Color.RED), 5, 6, 0);
        b17.setText(ss17);
        b16.setText("");
        String s18="رَقَبَۃٍ";
        SpannableString ss18=  new SpannableString(s18);
        ss18.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss18.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        ss18.setSpan(new ForegroundColorSpan(Color.MAGENTA), 2, 3, 0);
        ss18.setSpan(new ForegroundColorSpan(Color.MAGENTA), 3, 4, 0);
        ss18.setSpan(new ForegroundColorSpan(Color.BLUE), 4, 5, 0);
        ss18.setSpan(new ForegroundColorSpan(Color.BLUE), 5, 6, 0);
        ss18.setSpan(new ForegroundColorSpan(Color.BLACK), 6, 7, 0);
        ss18.setSpan(new ForegroundColorSpan(Color.BLACK), 7, 8, 0);
        b16.setText(ss18);
        b21.setText("");
        String s19="سُرُرٌ";
        SpannableString ss19=  new SpannableString(s19);
        ss19.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss19.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        ss19.setSpan(new ForegroundColorSpan(Color.BLUE), 2, 3, 0);
        ss19.setSpan(new ForegroundColorSpan(Color.BLUE), 3, 4, 0);
        ss19.setSpan(new ForegroundColorSpan(Color.MAGENTA), 4, 5, 0);
        ss19.setSpan(new ForegroundColorSpan(Color.MAGENTA), 5, 6, 0);
        b21.setText(ss19);
        b20.setText("");
        String s20="سَفَرَۃٍ";
        SpannableString ss20=  new SpannableString(s20);
        ss20.setSpan(new ForegroundColorSpan(Color.RED), 0, 1, 0);
        ss20.setSpan(new ForegroundColorSpan(Color.RED), 1, 2, 0);
        ss20.setSpan(new ForegroundColorSpan(Color.BLUE), 2, 3, 0);
        ss20.setSpan(new ForegroundColorSpan(Color.BLUE), 3, 4, 0);
        ss20.setSpan(new ForegroundColorSpan(Color.BLACK), 4, 5, 0);
        ss20.setSpan(new ForegroundColorSpan(Color.BLACK), 5, 6, 0);
        ss20.setSpan(new ForegroundColorSpan(Color.BLACK), 6, 7, 0);
        ss20.setSpan(new ForegroundColorSpan(Color.BLACK), 7, 8, 0);
        b20.setText(ss20);
        b19.setText("");
        String s21="صُحُفًا";
        SpannableString ss21=  new SpannableString(s21);
        ss21.setSpan(new ForegroundColorSpan(Color.RED), 0, 1, 0);
        ss21.setSpan(new ForegroundColorSpan(Color.RED), 1, 2, 0);
        ss21.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        ss21.setSpan(new ForegroundColorSpan(Color.BLACK), 3, 4, 0);
        ss21.setSpan(new ForegroundColorSpan(Color.BLUE), 4, 5, 0);
        ss21.setSpan(new ForegroundColorSpan(Color.BLUE), 5, 6, 0);
        ss21.setSpan(new ForegroundColorSpan(Color.BLACK), 6, 7, 0);
        b19.setText(ss21);
        b24.setText("");
        String s22="وَسَطًا";
        SpannableString ss22=  new SpannableString(s22);
        ss22.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss22.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        ss22.setSpan(new ForegroundColorSpan(Color.BLUE), 2, 3, 0);
        ss22.setSpan(new ForegroundColorSpan(Color.BLUE), 3, 4, 0);
        ss22.setSpan(new ForegroundColorSpan(Color.BLACK), 4, 5, 0);
        ss22.setSpan(new ForegroundColorSpan(Color.BLACK), 5, 6, 0);
        ss22.setSpan(new ForegroundColorSpan(Color.BLUE), 6, 7, 0);
        b24.setText(ss22);
        b23.setText("");
        String s23="طَبَقٍ";
        SpannableString ss23=  new SpannableString(s23);
        ss23.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        ss23.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        ss23.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        ss23.setSpan(new ForegroundColorSpan(Color.BLACK), 3, 4, 0);
        ss23.setSpan(new ForegroundColorSpan(Color.BLUE), 4, 5, 0);
        ss23.setSpan(new ForegroundColorSpan(Color.BLUE), 5, 6, 0);
        b23.setText(ss23);
        b22.setText("");
        String s24="طَبَقًا";
        SpannableString ss24=  new SpannableString(s24);
        ss24.setSpan(new ForegroundColorSpan(Color.MAGENTA), 0, 1, 0);
        ss24.setSpan(new ForegroundColorSpan(Color.MAGENTA), 1, 2, 0);
        ss24.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        ss24.setSpan(new ForegroundColorSpan(Color.BLACK), 3, 4, 0);
        ss24.setSpan(new ForegroundColorSpan(Color.BLUE), 4, 5, 0);
        ss24.setSpan(new ForegroundColorSpan(Color.BLUE), 5, 6, 0);
        ss24.setSpan(new ForegroundColorSpan(Color.BLACK), 6, 7, 0);
        b22.setText(ss24);
        b27.setText("");
        String s25="طُوًی";
        SpannableString ss25=  new SpannableString(s25);
        ss25.setSpan(new ForegroundColorSpan(Color.RED), 0, 1, 0);
        ss25.setSpan(new ForegroundColorSpan(Color.RED), 1, 2, 0);
        ss25.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        ss25.setSpan(new ForegroundColorSpan(Color.BLACK), 3, 4, 0);
        ss25.setSpan(new ForegroundColorSpan(Color.BLUE), 4, 5, 0);
        b27.setText(ss25);
        b26.setText("");
        String s26="عَبَسَ";
        SpannableString ss26=  new SpannableString(s26);
        ss26.setSpan(new ForegroundColorSpan(Color.MAGENTA), 0, 1, 0);
        ss26.setSpan(new ForegroundColorSpan(Color.MAGENTA), 1, 2, 0);
        ss24.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        ss24.setSpan(new ForegroundColorSpan(Color.BLACK), 3, 4, 0);
        ss24.setSpan(new ForegroundColorSpan(Color.RED), 4, 5, 0);
        ss24.setSpan(new ForegroundColorSpan(Color.RED), 5, 6, 0);
        b26.setText(ss26);
        b25.setText("");
        String s27="عَدَلَ";
        SpannableString ss27=  new SpannableString(s27);
        ss27.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        ss27.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        ss27.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        ss27.setSpan(new ForegroundColorSpan(Color.BLACK), 3, 4, 0);
        ss27.setSpan(new ForegroundColorSpan(Color.BLUE), 4, 5, 0);
        ss27.setSpan(new ForegroundColorSpan(Color.BLUE), 5, 6, 0);
        b25.setText(ss27);
        b30.setText("");
        String s28="عَلَقٍ";
        SpannableString ss28=  new SpannableString(s28);
        ss28.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss28.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        ss28.setSpan(new ForegroundColorSpan(Color.BLUE), 2, 3, 0);
        ss28.setSpan(new ForegroundColorSpan(Color.BLUE), 3, 4, 0);
        ss28.setSpan(new ForegroundColorSpan(Color.BLACK), 4, 5, 0);
        ss28.setSpan(new ForegroundColorSpan(Color.BLACK), 5, 6, 0);
        b30.setText(ss28);
        b29.setText("");
        String s29="عَمَدٍ";
        SpannableString ss29=  new SpannableString(s29);
        ss29.setSpan(new ForegroundColorSpan(Color.RED), 0, 1, 0);
        ss29.setSpan(new ForegroundColorSpan(Color.RED), 1, 2, 0);
        ss29.setSpan(new ForegroundColorSpan(Color.BLUE), 2, 3, 0);
        ss29.setSpan(new ForegroundColorSpan(Color.BLUE), 3, 4, 0);
        ss29.setSpan(new ForegroundColorSpan(Color.MAGENTA), 4, 5, 0);
        ss29.setSpan(new ForegroundColorSpan(Color.MAGENTA), 5, 6, 0);
        b29.setText(ss29);
        b28.setText("");
        String s30="عِنَبًا";
        SpannableString ss30=  new SpannableString(s30);
        ss30.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        ss30.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        ss30.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        ss30.setSpan(new ForegroundColorSpan(Color.BLACK), 3, 4, 0);
        ss30.setSpan(new ForegroundColorSpan(Color.BLUE), 4, 5, 0);
        ss30.setSpan(new ForegroundColorSpan(Color.BLUE), 5, 6, 0);
        ss30.setSpan(new ForegroundColorSpan(Color.BLACK), 6, 7, 0);
        b28.setText(ss30);
    }
}
