package com.example.islamiclovers;

import androidx.appcompat.app.AppCompatActivity;

import android.graphics.Color;
import android.os.Bundle;
import android.text.SpannableString;
import android.text.style.ForegroundColorSpan;
import android.widget.Button;

public class Moqataat extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_moqataat);
        Button b1 = (Button) findViewById(R.id.button1);
        Button b2 = (Button) findViewById(R.id.button2);
        Button b3 = (Button) findViewById(R.id.button3);
        Button b4 = (Button) findViewById(R.id.button4);
        Button b5 = (Button) findViewById(R.id.button5);
        Button b6 = (Button) findViewById(R.id.button6);
        Button b7 = (Button) findViewById(R.id.button7);
        Button b8 = (Button) findViewById(R.id.button8);
        Button b9 = (Button) findViewById(R.id.button9);
        Button b10 = (Button) findViewById(R.id.button10);
        Button b11 = (Button) findViewById(R.id.button11);
        Button b12 = (Button) findViewById(R.id.button12);
        Button b13 = (Button) findViewById(R.id.button13);
        Button b14 = (Button) findViewById(R.id.button14);
        b1.setText("");
        String s1 = "الٓمّٓصٓ";
        SpannableString ss1 = new SpannableString(s1);
        ss1.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        ss1.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        ss1.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        ss1.setSpan(new ForegroundColorSpan(Color.BLUE), 3, 4, 0);
        ss1.setSpan(new ForegroundColorSpan(Color.BLUE), 4, 5, 0);
        ss1.setSpan(new ForegroundColorSpan(Color.BLUE), 5, 6, 0);
        ss1.setSpan(new ForegroundColorSpan(Color.BLACK), 6, 7, 0);
        ss1.setSpan(new ForegroundColorSpan(Color.BLACK), 7, 8, 0);
        b1.setText(ss1);
        b2.setText("");
        String s2 = "الٓمّٓ";
        SpannableString ss2 = new SpannableString(s2);
        ss2.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss2.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        ss2.setSpan(new ForegroundColorSpan(Color.BLUE), 2, 3, 0);
        ss2.setSpan(new ForegroundColorSpan(Color.MAGENTA), 3, 4, 0);
        ss2.setSpan(new ForegroundColorSpan(Color.MAGENTA), 4, 5, 0);
        ss2.setSpan(new ForegroundColorSpan(Color.MAGENTA), 5, 6, 0);
        b2.setText(ss2);
        b3.setText("");
        String s3 = "الٓمّٓرٰ";
        SpannableString ss3 = new SpannableString(s3);
        ss3.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        ss3.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        ss3.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        ss3.setSpan(new ForegroundColorSpan(Color.MAGENTA), 3, 4, 0);
        ss3.setSpan(new ForegroundColorSpan(Color.MAGENTA), 4, 5, 0);
        ss3.setSpan(new ForegroundColorSpan(Color.MAGENTA), 5, 6, 0);
        ss3.setSpan(new ForegroundColorSpan(Color.BLACK), 6, 7, 0);
        ss3.setSpan(new ForegroundColorSpan(Color.BLACK), 7, 8, 0);
        b3.setText(ss3);
        b4.setText("");
        String s4 = "الٓرٰ";
        SpannableString ss4 = new SpannableString(s4);
        ss4.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        ss4.setSpan(new ForegroundColorSpan(Color.DKGRAY), 1, 2, 0);
        ss4.setSpan(new ForegroundColorSpan(Color.DKGRAY), 2, 3, 0);
        ss4.setSpan(new ForegroundColorSpan(Color.BLUE), 3, 4, 0);
        ss4.setSpan(new ForegroundColorSpan(Color.BLUE), 4, 5, 0);
        b4.setText(ss4);
        b5.setText("");
        String s5 = "طٰہٰ";
        SpannableString ss5 = new SpannableString(s5);
        ss5.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss5.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        ss5.setSpan(new ForegroundColorSpan(Color.BLUE), 2, 3, 0);
        ss5.setSpan(new ForegroundColorSpan(Color.BLUE), 3, 4, 0);
        b5.setText(ss5);
        b6.setText("");
        String s6 = "کٓھٓیٓعٓصٓ";
        SpannableString ss6 = new SpannableString(s6);
        ss6.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        ss6.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        ss6.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        ss6.setSpan(new ForegroundColorSpan(Color.BLACK), 3, 4, 0);
        ss6.setSpan(new ForegroundColorSpan(Color.BLUE), 4, 5, 0);
        ss6.setSpan(new ForegroundColorSpan(Color.BLUE), 5, 6, 0);
        ss6.setSpan(new ForegroundColorSpan(Color.MAGENTA), 6, 7, 0);
        ss6.setSpan(new ForegroundColorSpan(Color.MAGENTA), 7, 8, 0);
        ss6.setSpan(new ForegroundColorSpan(Color.GRAY), 8, 9, 0);
        ss6.setSpan(new ForegroundColorSpan(Color.GRAY), 9, 10, 0);
        b6.setText(ss6);
        b7.setText("");
        String s7 = "طٰسٰ";
        SpannableString ss7 = new SpannableString(s7);
        ss7.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        ss7.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        ss7.setSpan(new ForegroundColorSpan(Color.GRAY), 2, 3, 0);
        ss7.setSpan(new ForegroundColorSpan(Color.GRAY), 3, 4, 0);
        b7.setText(ss7);
        b8.setText("");
        String s8 = "طٰسٓمّٓ";
        SpannableString ss8 = new SpannableString(s8);
        ss8.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        ss8.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        ss8.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        ss8.setSpan(new ForegroundColorSpan(Color.BLACK), 3, 4, 0);
        ss8.setSpan(new ForegroundColorSpan(Color.MAGENTA), 4, 5, 0);
        ss8.setSpan(new ForegroundColorSpan(Color.MAGENTA), 5, 6, 0);
        ss8.setSpan(new ForegroundColorSpan(Color.MAGENTA), 6, 7, 0);
        b8.setText(ss8);
        b9.setText("");
        String s9 = "صٓ";
        SpannableString ss9 = new SpannableString(s9);
        ss9.setSpan(new ForegroundColorSpan(Color.MAGENTA), 0, 1, 0);
        ss9.setSpan(new ForegroundColorSpan(Color.MAGENTA), 1, 2, 0);
        b9.setText(ss9);
        b10.setText("");
        String s10 = "یٰسٓ";
        SpannableString ss10 = new SpannableString(s10);
        ss10.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss10.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        ss10.setSpan(new ForegroundColorSpan(Color.BLUE), 2, 3, 0);
        ss10.setSpan(new ForegroundColorSpan(Color.BLUE), 3, 4, 0);
        b10.setText(ss10);
        b11.setText("");
        String s11 = "عٓسٓقٓ";
        SpannableString ss11 = new SpannableString(s11);
        ss11.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss11.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        ss11.setSpan(new ForegroundColorSpan(Color.BLUE), 2, 3, 0);
        ss11.setSpan(new ForegroundColorSpan(Color.BLUE), 3, 4, 0);
        ss11.setSpan(new ForegroundColorSpan(Color.BLACK), 4, 5, 0);
        ss11.setSpan(new ForegroundColorSpan(Color.BLACK), 5, 6, 0);
        b11.setText(ss11);
        b12.setText("");
        String s12 = "حٰمٓ";
        SpannableString ss12 = new SpannableString(s12);
        ss12.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        ss12.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        ss12.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        ss12.setSpan(new ForegroundColorSpan(Color.BLACK), 3, 4, 0);
        b12.setText(ss12);
        b13.setText("");
        String s13 = "نٓ";
        SpannableString ss13 = new SpannableString(s13);
        ss13.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        ss13.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        b13.setText(ss13);
        b14.setText("");
        String s14 = "قٓ";
        SpannableString ss14 = new SpannableString(s14);
        ss14.setSpan(new ForegroundColorSpan(Color.MAGENTA), 0, 1, 0);
        ss14.setSpan(new ForegroundColorSpan(Color.MAGENTA), 1, 2, 0);
        b14.setText(ss14);
    }
}
