package com.example.islamiclovers;

import androidx.appcompat.app.AppCompatActivity;

import android.graphics.Color;
import android.os.Bundle;
import android.text.SpannableString;
import android.text.style.ForegroundColorSpan;
import android.widget.Button;

public class morakbaat extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_morakbaat);
        Button b1=(Button)findViewById(R.id.button1);
        Button b2=(Button)findViewById(R.id.button2);
        Button b3=(Button)findViewById(R.id.button3);
        Button b4=(Button)findViewById(R.id.button4);
        Button b5=(Button)findViewById(R.id.button5);
        Button b6=(Button)findViewById(R.id.button6);
        Button b7=(Button)findViewById(R.id.button7);
        Button b8=(Button)findViewById(R.id.button8);
        Button b9=(Button)findViewById(R.id.button9);
        Button b10=(Button)findViewById(R.id.button10);
        Button b11=(Button)findViewById(R.id.button11);
        Button b12=(Button)findViewById(R.id.button12);
        Button b13=(Button)findViewById(R.id.button13);
        Button b14=(Button)findViewById(R.id.button14);
        Button b15=(Button)findViewById(R.id.button15);
        Button b16=(Button)findViewById(R.id.button16);
        Button b17=(Button)findViewById(R.id.button17);
        Button b18=(Button)findViewById(R.id.button18);
        Button b19=(Button)findViewById(R.id.button19);
        Button b20=(Button)findViewById(R.id.button20);
        Button b21=(Button)findViewById(R.id.button21);
        Button b22=(Button)findViewById(R.id.button22);
        Button b23=(Button)findViewById(R.id.button23);
        Button b24=(Button)findViewById(R.id.button24);
        Button b25=(Button)findViewById(R.id.button25);
        Button b26=(Button)findViewById(R.id.button26);
        Button b27=(Button)findViewById(R.id.button27);
        Button b28=(Button)findViewById(R.id.button28);
        Button b29=(Button)findViewById(R.id.button29);
        Button b30=(Button)findViewById(R.id.button30);
        Button b31=(Button)findViewById(R.id.button31);
        Button b32=(Button)findViewById(R.id.button32);
        Button b33=(Button)findViewById(R.id.button33);
        Button b34=(Button)findViewById(R.id.button34);
        Button b35=(Button)findViewById(R.id.button35);
        Button b36=(Button)findViewById(R.id.button36);
        Button b37=(Button)findViewById(R.id.button37);
        Button b38=(Button)findViewById(R.id.button38);
        Button b39=(Button)findViewById(R.id.button39);
        Button b40=(Button)findViewById(R.id.button40);
        Button b41=(Button)findViewById(R.id.button41);
        Button b42=(Button)findViewById(R.id.button42);
        Button b43=(Button)findViewById(R.id.button43);
        Button b44=(Button)findViewById(R.id.button44);
        Button b45=(Button)findViewById(R.id.button45);
        Button b46=(Button)findViewById(R.id.button46);
        Button b47=(Button)findViewById(R.id.button47);
        Button b48=(Button)findViewById(R.id.button48);
        Button b49=(Button)findViewById(R.id.button49);
        Button b50=(Button)findViewById(R.id.button50);
        Button b51=(Button)findViewById(R.id.button51);
        Button b52=(Button)findViewById(R.id.button52);
        Button b53=(Button)findViewById(R.id.button53);
        Button b54=(Button)findViewById(R.id.button54);
        Button b55=(Button)findViewById(R.id.button55);
        Button b56=(Button)findViewById(R.id.button56);
        Button b57=(Button)findViewById(R.id.button57);
        Button b58=(Button)findViewById(R.id.button58);
        Button b59=(Button)findViewById(R.id.button59);
        Button b60=(Button)findViewById(R.id.button60);
        Button b61=(Button)findViewById(R.id.button61);
        Button b62=(Button)findViewById(R.id.button62);
        Button b63=(Button)findViewById(R.id.button63);
        Button b64=(Button)findViewById(R.id.button64);
        Button b65=(Button)findViewById(R.id.button65);
        Button b66=(Button)findViewById(R.id.button66);
        Button b67=(Button)findViewById(R.id.button67);
        Button b68=(Button)findViewById(R.id.button68);
        Button b69=(Button)findViewById(R.id.button69);
        Button b70=(Button)findViewById(R.id.button70);
        Button b71=(Button)findViewById(R.id.button71);
        Button b72=(Button)findViewById(R.id.button72);
        Button b73=(Button)findViewById(R.id.button73);
        Button b74=(Button)findViewById(R.id.button74);
        Button b75=(Button)findViewById(R.id.button75);
        Button b76=(Button)findViewById(R.id.button76);
        Button b77=(Button)findViewById(R.id.button77);
        Button b78=(Button)findViewById(R.id.button78);
        Button b79=(Button)findViewById(R.id.button79);
        Button b80=(Button)findViewById(R.id.button80);
        Button b81=(Button)findViewById(R.id.button81);
        Button b82=(Button)findViewById(R.id.button82);
        Button b83=(Button)findViewById(R.id.button83);
        Button b84=(Button)findViewById(R.id.button84);
        Button b85=(Button)findViewById(R.id.button85);
        Button b86=(Button)findViewById(R.id.button86);
        Button b87=(Button)findViewById(R.id.button87);
        Button b88=(Button)findViewById(R.id.button88);
        Button b89=(Button)findViewById(R.id.button89);
        Button b90=(Button)findViewById(R.id.button90);
        Button b91=(Button)findViewById(R.id.button91);
        Button b92=(Button)findViewById(R.id.button92);
        Button b93=(Button)findViewById(R.id.button93);
        Button b94=(Button)findViewById(R.id.button94);
        Button b95=(Button)findViewById(R.id.button95);
        Button b96=(Button)findViewById(R.id.button96);
        Button b97=(Button)findViewById(R.id.button97);
        Button b98=(Button)findViewById(R.id.button98);
        Button b99=(Button)findViewById(R.id.button99);
        Button b100=(Button)findViewById(R.id.button100);
        Button b101=(Button)findViewById(R.id.button101);
        Button b102=(Button)findViewById(R.id.button102);
        Button b103=(Button)findViewById(R.id.button103);
        Button b104=(Button)findViewById(R.id.button104);
        Button b105=(Button)findViewById(R.id.button105);
        Button b106=(Button)findViewById(R.id.button106);
        Button b107=(Button)findViewById(R.id.button107);
        Button b108=(Button)findViewById(R.id.button108);
        Button b109=(Button)findViewById(R.id.button109);
        Button b110=(Button)findViewById(R.id.button110);
        Button b111=(Button)findViewById(R.id.button111);
        Button b112=(Button)findViewById(R.id.button112);
        Button b113=(Button)findViewById(R.id.button113);
        Button b114=(Button)findViewById(R.id.button114);
        Button b115=(Button)findViewById(R.id.button115);
        Button b116=(Button)findViewById(R.id.button116);
        Button b117=(Button)findViewById(R.id.button117);
        Button b118=(Button)findViewById(R.id.button118);
        Button b119=(Button)findViewById(R.id.button119);
        Button b120=(Button)findViewById(R.id.button120);
        Button b121=(Button)findViewById(R.id.button121);
        Button b122=(Button)findViewById(R.id.button122);
        Button b123=(Button)findViewById(R.id.button123);
        b3.setText("ا");
        b2.setText("");
        String s2="لا";
        SpannableString ss2=  new SpannableString(s2);
        ss2.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss2.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        b2.setText(ss2);
        b1.setText("");
        String s3="لا";
        SpannableString ss3=  new SpannableString(s3);
        ss3.setSpan(new ForegroundColorSpan(Color.RED), 0, 1, 0);
        ss3.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        b1.setText(ss3);
        b6.setText("");
        String s4="با";
        SpannableString ss4=  new SpannableString(s4);
        ss4.setSpan(new ForegroundColorSpan(Color.RED), 0, 1, 0);
        ss4.setSpan(new ForegroundColorSpan(Color.DKGRAY), 1, 2, 0);
        b6.setText(ss4);
        b5.setText("");
        String s5="ل";
        SpannableString ss5=  new SpannableString(s5);
        ss5.setSpan(new ForegroundColorSpan(Color.MAGENTA), 0, 1, 0);
        b5.setText(ss5);
        b4.setText("");
        String s6="حح";
        SpannableString ss6=  new SpannableString(s6);
        ss6.setSpan(new ForegroundColorSpan(Color.MAGENTA), 0, 1, 0);
        ss6.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        b4.setText(ss6);
        b9.setText("");
        String s7="خ";
        SpannableString ss7=  new SpannableString(s7);
        ss7.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        b9.setText(ss7);
        b8.setText("");
        String s8="ج";
        SpannableString ss8=  new SpannableString(s8);
        ss8.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        b8.setText(ss8);
        b7.setText("");
        String s9="ح";
        SpannableString ss9=  new SpannableString(s9);
        ss9.setSpan(new ForegroundColorSpan(Color.RED), 0, 1, 0);
        b7.setText(ss9);
        b12.setText("");
        String s10="بلب";
        SpannableString ss10=  new SpannableString(s10);
        ss10.setSpan(new ForegroundColorSpan(Color.MAGENTA), 0, 1, 0);
        ss10.setSpan(new ForegroundColorSpan(Color.DKGRAY), 1, 2, 0);
        ss10.setSpan(new ForegroundColorSpan(Color.BLUE), 2, 3, 0);
        b12.setText(ss10);
        b11.setText("");
        String s11="ک";
        SpannableString ss11=  new SpannableString(s11);
        ss11.setSpan(new ForegroundColorSpan(Color.RED), 0, 1, 0);
        b11.setText(ss11);
        b10.setText("");
        String s12="ك";
        SpannableString ss12=  new SpannableString(s12);
        ss12.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        b10.setText(ss12);
        b15.setText("");
        String s13="ـكب";
        SpannableString ss13=  new SpannableString(s13);
        ss13.setSpan(new ForegroundColorSpan(Color.DKGRAY), 0, 1, 0);
        ss13.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        b15.setText(ss13);
        b14.setText("");
        String s14="كب";
        SpannableString ss14=  new SpannableString(s14);
        ss14.setSpan(new ForegroundColorSpan(Color.DKGRAY), 0, 1, 0);
        ss14.setSpan(new ForegroundColorSpan(Color.MAGENTA), 1, 2, 0);
        b14.setText(ss14);
        b13.setText("");
        String s15="كا";
        SpannableString ss15=  new SpannableString(s15);
        ss15.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss15.setSpan(new ForegroundColorSpan(Color.GREEN), 1, 2, 0);
        b13.setText(ss15);
        b18.setText("");
        String s16="کا";
        SpannableString ss16=  new SpannableString(s16);
        ss16.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss16.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        b18.setText(ss16);
        b17.setText("");
        String s17="کبت";
        SpannableString ss17=  new SpannableString(s17);
        ss17.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        ss17.setSpan(new ForegroundColorSpan(Color.MAGENTA), 1, 2, 0);
        ss17.setSpan(new ForegroundColorSpan(Color.BLUE), 2, 3, 0);
        b17.setText(ss17);
        b16.setText("");
        String s18="تکث";
        SpannableString ss18=  new SpannableString(s18);
        ss18.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss18.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        ss18.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        b16.setText(ss18);
        b21.setText("");
        String s19="ب";
        SpannableString ss19=  new SpannableString(s19);
        ss19.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        b21.setText(ss19);
        b20.setText("");
        String s20="ت";
        SpannableString ss20=  new SpannableString(s20);
        ss20.setSpan(new ForegroundColorSpan(Color.RED), 0, 1, 0);
        b20.setText(ss20);
        b19.setText("");
        String s21="ث";
        SpannableString ss21=  new SpannableString(s21);
        ss18.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        b19.setText(ss21);
        b24.setText("");
        String s22="ن";
        SpannableString ss22=  new SpannableString(s22);
        ss22.setSpan(new ForegroundColorSpan(Color.MAGENTA), 0, 1, 0);
        b24.setText(ss22);
        b23.setText("");
        String s23="ی";
        SpannableString ss23=  new SpannableString(s23);
        ss23.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        b23.setText(ss23);
        b22.setText("");
        String s24="با";
        SpannableString ss24=  new SpannableString(s24);
        ss24.setSpan(new ForegroundColorSpan(Color.GREEN), 0, 1, 0);
        ss24.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        b22.setText(ss24);
        b27.setText("");
        String s25="نا";
        SpannableString ss25=  new SpannableString(s25);
        ss25.setSpan(new ForegroundColorSpan(Color.DKGRAY), 0, 1, 0);
        ss25.setSpan(new ForegroundColorSpan(Color.RED), 1, 2, 0);
        b27.setText(ss25);
        b26.setText("");
        String s26="تا";
        SpannableString ss26=  new SpannableString(s26);
        ss26.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        ss26.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        b26.setText(ss26);
        b25.setText("");
        String s27="یا";
        SpannableString ss27=  new SpannableString(s27);
        ss27.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss27.setSpan(new ForegroundColorSpan(Color.RED), 1, 2, 0);
        b25.setText(ss27);
        b30.setText("");
        String s28="ثا";
        SpannableString ss28=  new SpannableString(s28);
        ss28.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        ss28.setSpan(new ForegroundColorSpan(Color.RED), 1, 2, 0);
        b30.setText(ss28);
        b29.setText("");
        String s29="بس";
        SpannableString ss29=  new SpannableString(s29);
        ss29.setSpan(new ForegroundColorSpan(Color.MAGENTA), 0, 1, 0);
        ss29.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        b29.setText(ss29);
        b28.setText("");
        String s30="یس";
        SpannableString ss30=  new SpannableString(s30);
        ss30.setSpan(new ForegroundColorSpan(Color.GREEN), 0, 1, 0);
        ss30.setSpan(new ForegroundColorSpan(Color.RED), 1, 2, 0);
        b28.setText(ss30);
        b32.setText("");
        b33.setText("");
        String s31="نس";
        SpannableString ss31=  new SpannableString(s31);
        ss31.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        ss31.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        b33.setText(ss31);
        String s32="تس";
        SpannableString ss32=  new SpannableString(s32);
        ss32.setSpan(new ForegroundColorSpan(Color.RED), 0, 1, 0);
        ss32.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        b32.setText(ss32);
        b31.setText("");
        String s33="ثس";
        SpannableString ss33=  new SpannableString(s33);
        ss33.setSpan(new ForegroundColorSpan(Color.DKGRAY), 0, 1, 0);
        ss33.setSpan(new ForegroundColorSpan(Color.RED), 1, 2, 0);
        b31.setText(ss33);
        b36.setText("");
        String s34="ثج";
        SpannableString ss34=  new SpannableString(s34);
        ss34.setSpan(new ForegroundColorSpan(Color.DKGRAY), 0, 1, 0);
        ss34.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        b36.setText(ss34);
        b35.setText("");
        String s35="تح";
        SpannableString ss35=  new SpannableString(s35);
        ss35.setSpan(new ForegroundColorSpan(Color.GREEN), 0, 1, 0);
        ss35.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        b35.setText(ss35);
        b34.setText("");
        String s36="خح";
        SpannableString ss36=  new SpannableString(s36);
        ss36.setSpan(new ForegroundColorSpan(Color.DKGRAY), 0, 1, 0);
        ss36.setSpan(new ForegroundColorSpan(Color.GREEN), 1, 2, 0);
        b34.setText(ss36);
        b39.setText("");
        String s37="یح";
        SpannableString ss37=  new SpannableString(s37);
        ss37.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        ss37.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        b39.setText(ss37);
        b38.setText("");
        String s38="بج";
        SpannableString ss38=  new SpannableString(s38);
        ss38.setSpan(new ForegroundColorSpan(Color.DKGRAY), 0, 1, 0);
        ss38.setSpan(new ForegroundColorSpan(Color.GREEN), 1, 2, 0);
        b38.setText(ss38);
        b37.setText("");
        String s39="یم";
        SpannableString ss39=  new SpannableString(s39);
        ss39.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        ss39.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        b37.setText(ss39);
        b42.setText("");
        String s40="بم";
        SpannableString ss40=  new SpannableString(s40);
        ss40.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss40.setSpan(new ForegroundColorSpan(Color.RED), 1, 2, 0);
        b42.setText(ss40);
        b41.setText("");
        String s41="نم";
        SpannableString ss41=  new SpannableString(s41);
        ss41.setSpan(new ForegroundColorSpan(Color.DKGRAY), 0, 1, 0);
        ss41.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        b41.setText(ss41);
        b40.setText("");
        String s42="تم";
        SpannableString ss42=  new SpannableString(s42);
        ss42.setSpan(new ForegroundColorSpan(Color.GREEN), 0, 1, 0);
        ss42.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        b40.setText(ss42);
        b45.setText("");
        String s43="ثم";
        SpannableString ss43=  new SpannableString(s43);
        ss43.setSpan(new ForegroundColorSpan(Color.MAGENTA), 0, 1, 0);
        ss43.setSpan(new ForegroundColorSpan(Color.RED), 1, 2, 0);
        b45.setText(ss43);
        b44.setText("");
        String s44="بی";
        SpannableString ss44=  new SpannableString(s44);
        ss44.setSpan(new ForegroundColorSpan(Color.GRAY), 0, 1, 0);
        ss44.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        b44.setText(ss44);
        b43.setText("");
        String s45="یی";
        SpannableString ss45=  new SpannableString(s45);
        ss45.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        ss45.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        b43.setText(ss45);
        b48.setText("");
        String s46="نی";
        SpannableString ss46=  new SpannableString(s46);
        ss46.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        ss46.setSpan(new ForegroundColorSpan(Color.RED), 1, 2, 0);
        b48.setText(ss46);
        b47.setText("");
        String s47="تی";
        SpannableString ss47=  new SpannableString(s47);
        ss47.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss47.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        b47.setText(ss47);
        b46.setText("");
        String s48="ثی";
        SpannableString ss48=  new SpannableString(s48);
        ss48.setSpan(new ForegroundColorSpan(Color.MAGENTA), 0, 1, 0);
        ss48.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        b46.setText(ss48);
        b51.setText("");
        String s49="نبل";
        SpannableString ss49=  new SpannableString(s49);
        ss49.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        ss49.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        ss49.setSpan(new ForegroundColorSpan(Color.RED), 2, 3, 0);
        b51.setText(ss49);
        b50.setText("");
        String s50="ثنل";
        SpannableString ss50=  new SpannableString(s50);
        ss50.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss50.setSpan(new ForegroundColorSpan(Color.RED), 1, 2, 0);
        ss50.setSpan(new ForegroundColorSpan(Color.BLUE), 2, 3, 0);
        b50.setText(ss50);
        b49.setText("");
        String s51="نیل";
        SpannableString ss51=  new SpannableString(s51);
        ss51.setSpan(new ForegroundColorSpan(Color.MAGENTA), 0, 1, 0);
        ss51.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        ss50.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        b49.setText(ss51);
        b54.setText("");
        String s52="یتل";
        SpannableString ss52=  new SpannableString(s52);
        ss52.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        ss52.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        ss52.setSpan(new ForegroundColorSpan(Color.BLUE), 2, 3, 0);
        b54.setText(ss52);
        b53.setText("");
        String s53="ثتل";
        SpannableString ss53=  new SpannableString(s53);
        ss53.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss53.setSpan(new ForegroundColorSpan(Color.RED), 1, 2, 0);
        ss53.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        b53.setText(ss53);
        b52.setText("");
        String s54="نبن";
        SpannableString ss54=  new SpannableString(s54);
        ss54.setSpan(new ForegroundColorSpan(Color.MAGENTA), 0, 1, 0);
        ss54.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        ss54.setSpan(new ForegroundColorSpan(Color.MAGENTA), 2, 3, 0);
        b52.setText(ss54);
        b57.setText("");
        String s55="بنن";
        SpannableString ss55=  new SpannableString(s55);
        ss55.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss55.setSpan(new ForegroundColorSpan(Color.DKGRAY), 1, 2, 0);
        ss55.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        b57.setText(ss55);
        b56.setText("");
        String s56="تین";
        SpannableString ss56=  new SpannableString(s56);
        ss56.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss56.setSpan(new ForegroundColorSpan(Color.RED), 1, 2, 0);
        ss56.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        b56.setText(ss56);
        b55.setText("");
        String s57="یتن";
        SpannableString ss57=  new SpannableString(s57);
        ss57.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss57.setSpan(new ForegroundColorSpan(Color.GREEN), 1, 2, 0);
        ss57.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        b55.setText(ss57);
        b60.setText("");
        String s58="ثثن";
        SpannableString ss58=  new SpannableString(s58);
        ss58.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss58.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        ss58.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        b60.setText(ss58);
        b59.setText("");
        String s59="حث";
        SpannableString ss59=  new SpannableString(s59);
        ss59.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        ss59.setSpan(new ForegroundColorSpan(Color.MAGENTA), 1, 2, 0);
        b59.setText(ss59);
        b58.setText("");
        String s60="خب";
        SpannableString ss60=  new SpannableString(s60);
        ss60.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss60.setSpan(new ForegroundColorSpan(Color.RED), 1, 2, 0);
        b58.setText(ss60);
        b63.setText("");
        String s61="جت";
        SpannableString ss61=  new SpannableString(s61);
        ss61.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss61.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        b63.setText(ss61);
        b62.setText("");
        String s62="تجت";
        SpannableString ss62=  new SpannableString(s62);
        ss62.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        ss62.setSpan(new ForegroundColorSpan(Color.GREEN), 1, 2, 0);
        ss62.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        b62.setText(ss62);
        b61.setText("");
        String s63="یجت";
        SpannableString ss63=  new SpannableString(s63);
        ss63.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss63.setSpan(new ForegroundColorSpan(Color.GRAY), 1, 2, 0);
        ss63.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        b61.setText(ss63);
        b66.setText("");
        String s64="بخت";
        SpannableString ss64=  new SpannableString(s64);
        ss64.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss64.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        ss64.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        b66.setText(ss64);
        b65.setText("");
        String s65="ۃ";
        SpannableString ss65=  new SpannableString(s65);
        ss65.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        b65.setText(ss65);
        b64.setText("");
        String s66="ہ";
        SpannableString ss66=  new SpannableString(s66);
        ss66.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        b64.setText(ss66);
        b69.setText("");
        String s67="بۃ";
        SpannableString ss67=  new SpannableString(s67);
        ss67.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss67.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        b69.setText(ss67);
        b68.setText("");
        String s68="یہ";
        SpannableString ss68=  new SpannableString(s68);
        ss68.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        ss68.setSpan(new ForegroundColorSpan(Color.MAGENTA), 1, 2, 0);
        b68.setText(ss68);
        b67.setText("");
        String s69="تہ";
        SpannableString ss69=  new SpannableString(s69);
        ss69.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss69.setSpan(new ForegroundColorSpan(Color.GRAY), 1, 2, 0);
        b67.setText(ss69);
        b72.setText("");
        String s70="نۃ";
        SpannableString ss70=  new SpannableString(s70);
        ss70.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss70.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        b72.setText(ss70);
        b71.setText("");
        String s71="ھ";
        SpannableString ss71=  new SpannableString(s71);
        ss71.setSpan(new ForegroundColorSpan(Color.MAGENTA), 0, 1, 0);
        b71.setText(ss71);
        b70.setText("");
        String s72="یھب";
        SpannableString ss72=  new SpannableString(s72);
        ss72.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss72.setSpan(new ForegroundColorSpan(Color.GREEN), 1, 2, 0);
        ss72.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        b70.setText(ss72);
        b75.setText("");
        String s73="بھا";
        SpannableString ss73=  new SpannableString(s73);
        ss73.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        ss73.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        ss73.setSpan(new ForegroundColorSpan(Color.BLUE), 2, 3, 0);
        b75.setText(ss73);
        b74.setText("");
        String s74="بھم";
        SpannableString ss74=  new SpannableString(s74);
        ss74.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss74.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        ss74.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        b74.setText(ss74);
        b73.setText("");
        String s75="د";
        SpannableString ss75=  new SpannableString(s75);
        ss75.setSpan(new ForegroundColorSpan(Color.MAGENTA), 0, 1, 0);
        b73.setText(ss75);
        b78.setText("");
        String s76="ذ";
        SpannableString ss76=  new SpannableString(s76);
        ss76.setSpan(new ForegroundColorSpan(Color.MAGENTA), 0, 1, 0);
        b78.setText(ss76);
        b77.setText("");
        String s77="جد";
        SpannableString ss77=  new SpannableString(s77);
        ss77.setSpan(new ForegroundColorSpan(Color.RED), 0, 1, 0);
        ss77.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        b77.setText(ss77);
        b76.setText("");
        String s78="خذ";
        SpannableString ss78=  new SpannableString(s78);
        ss78.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss78.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        b76.setText(ss78);
        b81.setText("");
        String s79="ر";
        SpannableString ss79=  new SpannableString(s79);
        ss79.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        b81.setText(ss79);
        b80.setText("");
        String s80="ز";
        SpannableString ss80=  new SpannableString(s80);
        ss80.setSpan(new ForegroundColorSpan(Color.GREEN), 0, 1, 0);
        b80.setText(ss80);
        b79.setText("");
        String s81="جر";
        SpannableString ss81=  new SpannableString(s81);
        ss81.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss81.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        b79.setText(ss81);
        b84.setText("");
        String s82="خز";
        SpannableString ss82=  new SpannableString(s82);
        ss82.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss82.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        b84.setText(ss82);
        b83.setText("");
        String s83="ر";
        SpannableString ss83=  new SpannableString(s83);
        ss83.setSpan(new ForegroundColorSpan(Color.RED), 0, 1, 0);
        b83.setText(ss83);
        b82.setText("");
        String s84="ز";
        SpannableString ss84=  new SpannableString(s80);
        ss84.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        b82.setText(ss84);
        b87.setText("");
        String s85="یر";
        SpannableString ss85=  new SpannableString(s85);
        ss85.setSpan(new ForegroundColorSpan(Color.RED), 0, 1, 0);
        ss85.setSpan(new ForegroundColorSpan(Color.GREEN), 1, 2, 0);
        b87.setText(ss85);
        b86.setText("");
        String s86="تز";
        SpannableString ss86=  new SpannableString(s86);
        ss86.setSpan(new ForegroundColorSpan(Color.GREEN), 0, 1, 0);
        ss86.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        b86.setText(ss86);
        b85.setText("");
        String s87="س";
        SpannableString ss87=  new SpannableString(s87);
        ss87.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        b85.setText(ss87);
        b90.setText("");
        String s88="ش";
        SpannableString ss88=  new SpannableString(s88);
        ss87.setSpan(new ForegroundColorSpan(Color.CYAN), 0, 1, 0);
        b90.setText(ss88);
        b89.setText("");
        String s89="سل";
        SpannableString ss89=  new SpannableString(s89);
        ss89.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss89.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        b89.setText(ss89);
        b88.setText("");
        String s90="شل";
        SpannableString ss90=  new SpannableString(s90);
        ss90.setSpan(new ForegroundColorSpan(Color.RED), 0, 1, 0);
        ss90.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        b88.setText(ss90);
        b93.setText("");
        String s91="ص";
        SpannableString ss91=  new SpannableString(s91);
        ss91.setSpan(new ForegroundColorSpan(Color.RED), 0, 1, 0);
        b93.setText(ss91);
        b92.setText("");
        String s92="ض";
        SpannableString ss92=  new SpannableString(s92);
        ss92.setSpan(new ForegroundColorSpan(Color.MAGENTA), 0, 1, 0);
        b92.setText(ss92);
        b91.setText("");
        String s93="ط";
        SpannableString ss93=  new SpannableString(s93);
        ss93.setSpan(new ForegroundColorSpan(Color.GREEN), 0, 1, 0);
        b91.setText(ss93);
        b96.setText("");
        String s94="ظ";
        SpannableString ss94=  new SpannableString(s94);
        ss94.setSpan(new ForegroundColorSpan(Color.CYAN), 0, 1, 0);
        b96.setText(ss94);
        b95.setText("");
        String s95="صب";
        SpannableString ss95=  new SpannableString(s90);
        ss95.setSpan(new ForegroundColorSpan(Color.RED), 0, 1, 0);
        ss95.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        b95.setText(ss95);
        b94.setText("");
        String s96="طب";
        SpannableString ss96=  new SpannableString(s96);
        ss96.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss96.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        b94.setText(ss96);
        b99.setText("");
        String s97="ضا";
        SpannableString ss97=  new SpannableString(s97);
        ss97.setSpan(new ForegroundColorSpan(Color.DKGRAY), 0, 1, 0);
        ss97.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        b99.setText(ss97);
        b98.setText("");
        String s98="ظا";
        SpannableString ss98=  new SpannableString(s98);
        ss98.setSpan(new ForegroundColorSpan(Color.RED), 0, 1, 0);
        ss98.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        b98.setText(ss98);
        b97.setText("");
        String s99="ع";
        SpannableString ss99=  new SpannableString(s99);
        ss99.setSpan(new ForegroundColorSpan(Color.MAGENTA), 0, 1, 0);
        b97.setText(ss99);
        b102.setText("");
        String s100="غ";
        SpannableString ss100=  new SpannableString(s100);
        ss100.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        b102.setText(ss100);
        b101.setText("");
        String s101="ء";
        SpannableString ss101=  new SpannableString(s101);
        ss101.setSpan(new ForegroundColorSpan(Color.RED), 0, 1, 0);
        b101.setText(ss101);
        b100.setText("");
        String s102="عز";
        SpannableString ss102=  new SpannableString(s102);
        ss102.setSpan(new ForegroundColorSpan(Color.MAGENTA), 0, 1, 0);
        ss102.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        b100.setText(ss102);
        b105.setText("");
        String s103="غر";
        SpannableString ss103=  new SpannableString(s103);
        ss103.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        ss103.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        b105.setText(ss103);
        b104.setText("");
        String s104="صع";
        SpannableString ss104=  new SpannableString(s104);
        ss104.setSpan(new ForegroundColorSpan(Color.RED), 0, 1, 0);
        ss104.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        b104.setText(ss104);
        b103.setText("");
        String s105="صغ";
        SpannableString ss105=  new SpannableString(s105);
        ss105.setSpan(new ForegroundColorSpan(Color.MAGENTA), 0, 1, 0);
        ss105.setSpan(new ForegroundColorSpan(Color.RED), 1, 2, 0);
        b103.setText(ss105);
        b108.setText("");
        String s106="بعد";
        SpannableString ss106=  new SpannableString(s106);
        ss106.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        ss106.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        ss106.setSpan(new ForegroundColorSpan(Color.BLUE), 2, 3, 0);
        b108.setText(ss106);
        b107.setText("");
        String s107="تٖغد";
        SpannableString ss107=  new SpannableString(s107);
        ss107.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss107.setSpan(new ForegroundColorSpan(Color.CYAN), 1, 2, 0);
        ss107.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        b107.setText(ss107);
        b106.setText("");
        String s108="أ";
        SpannableString ss108=  new SpannableString(s108);
        ss108.setSpan(new ForegroundColorSpan(Color.RED), 0, 1, 0);
        b106.setText(ss108);
        b111.setText("");
        String s109="ؤ";
        SpannableString ss109=  new SpannableString(s109);
        ss109.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        b111.setText(ss109);
        b110.setText("");
        String s110="ئ";
        SpannableString ss110=  new SpannableString(s110);
        ss108.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        b110.setText(ss110);
        b109.setText("");
        String s111="ف";
        SpannableString ss111=  new SpannableString(s111);
        ss111.setSpan(new ForegroundColorSpan(Color.MAGENTA), 0, 1, 0);
        b109.setText(ss111);
        b114.setText("");
        String s112="ق";
        SpannableString ss112=  new SpannableString(s112);
        ss112.setSpan(new ForegroundColorSpan(Color.RED), 0, 1, 0);
        b114.setText(ss112);
        b113.setText("");
        String s113="و";
        SpannableString ss113=  new SpannableString(s113);
        ss113.setSpan(new ForegroundColorSpan(Color.CYAN), 0, 1, 0);
        b113.setText(ss113);
        b112.setText("");
        String s114="قو";
        SpannableString ss114=  new SpannableString(s114);
        ss114.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        ss114.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        b112.setText(ss114);
        b117.setText("");
        String s115="فو";
        SpannableString ss115=  new SpannableString(s115);
        ss115.setSpan(new ForegroundColorSpan(Color.GREEN), 0, 1, 0);
        ss115.setSpan(new ForegroundColorSpan(Color.BLACK), 1, 2, 0);
        b117.setText(ss115);
        b116.setText("");
        String s116="فقل";
        SpannableString ss116=  new SpannableString(s116);
        ss116.setSpan(new ForegroundColorSpan(Color.BLUE), 0, 1, 0);
        ss116.setSpan(new ForegroundColorSpan(Color.GREEN), 1, 2, 0);
        ss116.setSpan(new ForegroundColorSpan(Color.BLUE), 2, 3, 0);
        b116.setText(ss116);
        b115.setText("");
        String s117="قفل";
        SpannableString ss117=  new SpannableString(s117);
        ss117.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss117.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        ss117.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        b115.setText(ss117);
        b120.setText("");
        String s118="یف";
        SpannableString ss118=  new SpannableString(s118);
        ss118.setSpan(new ForegroundColorSpan(Color.MAGENTA), 0, 1, 0);
        ss118.setSpan(new ForegroundColorSpan(Color.RED), 1, 2, 0);
        b120.setText(ss118);
        b119.setText("");
        String s119="م";
        SpannableString ss119=  new SpannableString(s119);
        ss119.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        b119.setText(ss119);
        b118.setText("");
        String s120="حم";
        SpannableString ss120=  new SpannableString(s120);
        ss120.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss120.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        b118.setText(ss120);
        b123.setText("");
        String s121="لم";
        SpannableString ss121=  new SpannableString(s121);
        ss121.setSpan(new ForegroundColorSpan(Color.MAGENTA), 0, 1, 0);
        ss121.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        b123.setText(ss121);
        b122.setText("");
        String s122="تم";
        SpannableString ss122=  new SpannableString(s122);
        ss122.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss122.setSpan(new ForegroundColorSpan(Color.RED), 1, 2, 0);
        b122.setText(ss122);
        b121.setText("");
        String s123="تمت";
        SpannableString ss123=  new SpannableString(s123);
        ss123.setSpan(new ForegroundColorSpan(Color.BLACK), 0, 1, 0);
        ss123.setSpan(new ForegroundColorSpan(Color.BLUE), 1, 2, 0);
        ss123.setSpan(new ForegroundColorSpan(Color.BLACK), 2, 3, 0);
        b121.setText(ss123);
    }
}
